### ISSUE TITLE
Flags

### ISSUE THREAD

**Issue by pmknowles** [steineey/node-red-contrib-email#2]
Thanks for a really useful node.
A couple of points.
The docs don't make it clear that you must put a 'from' email address into the node for the email to be accepted (at least for Outlook).
The other is, is it possible to set the Important flag? Some messages are more critical  than others...

**Comment by csteinba** [comment]
Thank you for your feedback.
I'm not 100% if 'from' is mandatory in any scenario. I think it depends on your SMTP server or email client.
I added a 'important flag' feature. Nodemailer calls it `priority`. You can now set a priority on each message: 'normal' (default), 'high' and 'low'. Set the priority in the node ui or with `msg.email.priority`, if you want to set the priority individually on each message. Please update to `node-red-contrib-email@0.3.1`.

**Comment by pmknowles** [comment]
Thank you for the speedy response. Certainly for outlook.com I get a 'Success' message but no email is sent unless there's a valif 'from' address xxx@outlook.com (not enough to put a string in)
